version: '3'
services:
  nextjs:
    build: .
    volumes:
      - nextjs_build:/app/.next
    ports:
      - '3000:3000'
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - nextjs_build:/usr/share/nginx/html/_next
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    command:
      [
        '/bin/sh',
        '-c',
        "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'",
      ]
    depends_on:
      - nextjs
    networks:
      - webnet

volumes:
  nextjs_build: {}

networks:
  webnet:
