import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
// 전역 CSS
import '@/_shared/components/ui/globals.css'
import SideNavigation from '@/_widgets/sideNavigation/ui/SideNavigation'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SideNavigation />
        {children}
      </body>
    </html>
  )
}
