name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main # 또는 특정 브랜치 이름을 지정할 수 있습니다

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          MODEL: gpt-3.5-turbo
